import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import { notify } from '@/lib/confirm';

// Render an HTML string to a PDF and hand it to the OS share sheet (save,
// WhatsApp, email, print). On web there is no share sheet, so we open the
// browser's print-to-PDF dialog instead.
export async function exportPdf(html: string) {
  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({ html });
      return;
    }
    const { uri } = await Print.printToFileAsync({ html });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share report' });
    } else {
      notify('PDF saved but sharing is not available on this device.');
    }
  } catch (e) {
    console.error('PDF export failed', e);
    notify('Could not generate the PDF.');
  }
}

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string)
  );

// Shared document chrome: company header, report title/subtitle and print styles.
export function reportDocument(opts: {
  companyName: string;
  companyPhone?: string;
  title: string;
  subtitle?: string;
  body: string;
}) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    * { font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; }
    body { padding: 28px; color: #222; }
    .brand { font-size: 22px; font-weight: 800; }
    .muted { color: #777; }
    h2 { margin: 4px 0 0; font-size: 18px; }
    table { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 13px; }
    th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e5e5; }
    th { background: #f5f5f5; text-transform: uppercase; font-size: 11px; letter-spacing: .04em; color: #555; }
    .r { text-align: right; }
    tfoot td { font-weight: 700; border-top: 2px solid #222; border-bottom: none; }
    .kpis { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 14px; }
    .kpi { border: 1px solid #e5e5e5; border-radius: 8px; padding: 12px 16px; min-width: 130px; }
    .kpi .label { font-size: 11px; color: #777; text-transform: uppercase; }
    .kpi .value { font-size: 20px; font-weight: 800; margin-top: 2px; }
    .foot { margin-top: 28px; font-size: 11px; color: #999; }
  </style></head><body>
    <div class="brand">${esc(opts.companyName)}</div>
    <h2>${esc(opts.title)}</h2>
    ${opts.subtitle ? `<div class="muted">${esc(opts.subtitle)}</div>` : ''}
    ${opts.body}
    <div class="foot">Generated by Electron POS${opts.companyPhone ? ` · ${esc(opts.companyPhone)}` : ''}</div>
  </body></html>`;
}

export { esc as escapeHtml };
